spring.application.name=vendas
server.port=8082

spring.data.mongodb.uri=mongodb://localhost:27017/db_vendas

# Integrações com outros microserviços
clientes.url=http://localhost:8080
produtos.url=http://localhost:8081

# Configurações do RabbitMQ (Producer)
spring.rabbitmq.host=localhost
spring.rabbitmq.port=5672
spring.rabbitmq.username=guest
spring.rabbitmq.password=guest
spring.rabbitmq.template.retry.enabled=true

jwt.secret=c3VhLWNoYXZlLXNlY3JldGEtc3VwZXItc2VndXJhLXF1ZS1kZXZlLXNlci1iZW0tbG9uZ2E=
springdoc.swagger-ui.path=/swagger-ui.html

# Debug e Logs
debug=false
logging.level.org.springframework.boot.diagnostics=DEBUG